=== BackupTheBerlios/siri-svn/trunk/modules/fatview/src/schema/irisclient.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 2 U (http://www.xmlspy.com) by Registred (Registred) -->
<!--W3C Schema generated by XMLSPY v5 rel. 2 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="address">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="127.0.0.1"/>
				<xs:enumeration value="preas01"/>
				<xs:enumeration value="tdvas02"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="description" type="xs:string"/>
	<xs:element name="developer" type="xs:string"/>
	<xs:element name="irisclient">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="versioninfo" type="versioninfoType"/>
				<xs:element ref="title"/>
				<xs:element ref="pingservices"/>
                <xs:element name="lookandfeel" type="lookandfeelType" maxOccurs="unbounded"/>
				<xs:element name="irisserver" type="irisserverType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

    <!-- look and feel settings -->
    <xs:complexType name="lookandfeelType">
		<xs:sequence>
			<xs:element ref="lookandfeelthemepath"/>
			<xs:element ref="type"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="lookandfeelthemepath" type="xs:string"/>
    <xs:element name="type">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="aqua"/>
				<xs:enumeration value="kuhnstoff"/>
                <xs:enumeration value="metal"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:complexType name="irisserverType">
		<xs:sequence>
			<xs:element ref="name"/>
			<xs:element ref="description"/>
			<xs:element ref="address"/>
			<xs:element ref="loggingport"/>
			<xs:element ref="rmiservice"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="loggingport" type="xs:short"/>
	<xs:element name="name">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="localdevelopment"/>
				<xs:enumeration value="prodserver_tdvas01"/>
				<xs:enumeration value="test_preas01"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="pingservices" type="xs:short"/>
	<xs:element name="releasedate" type="xs:date"/>
	<xs:element name="rmiservice">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="//preas01/iris"/>
				<xs:enumeration value="//tdvas02/iris"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="title" type="xs:string"/>
	<xs:element name="version" type="xs:string"/>
	<xs:complexType name="versioninfoType">
		<xs:sequence>
			<xs:element ref="version"/>
			<xs:element ref="releasedate"/>
			<xs:element ref="developer"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== BackupTheBerlios/siri-svn/trunk/modules/fatview/src/conf/fatview.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<irisclient xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="C:/gepo/mycvsprojects/iris/modules/swing-client/src/schema/irisclient.xsd">

    <versioninfo>
        <version>1.0.0</version>
        <releasedate>2004-02-01</releasedate>
        <developer>Georges Polyzois Wilhelm</developer>
    </versioninfo>

    <title>Iris client</title>
    <pingservices>30000</pingservices>
    <!-- path for development - look in maven repos-->
    <lookandfeel>
        <lookandfeelthemepath>C:/Documents and Settings/gepo/.maven/repository/lookandfeel/jars/</lookandfeelthemepath>
        <!-- type>aqua</type-->
        <!--type>kuhnstoff</type -->
        <type>themepack</type>
    </lookandfeel>
    <irisserver>
        <name>localdevelopment</name>
        <description>Development local server</description>
        <address>127.0.0.1</address>
        <loggingport>4560</loggingport>
        <rmiservice>//127.0.0.1/iris</rmiservice>
    </irisserver>
    <irisserver>
        <name>test_preas01</name>
        <description>Development local server</description>
        <address>preas01</address>
        <loggingport>4560</loggingport>
        <rmiservice>//preas01/iris</rmiservice>
    </irisserver>
    <irisserver>
        <name>prodserver_tdvas01</name>
        <description>Live server</description>
        <address>tdvas02</address>
        <loggingport>4560</loggingport>
        <rmiservice>//tdvas02/iris</rmiservice>
    </irisserver>
    <irisserver>
        <name>TEST</name>
        <description>TESTDESC</description>
        <address>sdafklhasdjfh</address>
        <loggingport>4560</loggingport>
        <rmiservice>rmi</rmiservice>
    </irisserver>
    <irisserver>
        <name>TEST</name>
        <description>station</description>
        <address/>
        <loggingport>4560</loggingport>
        <rmiservice>//zeus2:1971/iris</rmiservice>
    </irisserver>
</irisclient>

=== BackupTheBerlios/siri-svn/trunk/modules/swing-client/src/test_/irisclienttest.xml
<?xml version="1.0" encoding="UTF-8"?>
<irisclient xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Documents and Settings\gepo\My Documents\irisclient.xsd">
	<versioninfo>
		<version>1.0.0</version>
		<releasedate>2004-02-01</releasedate>
		<developer>gollum</developer>
	</versioninfo>
	<title>Iris client</title>
	<pingservices>30000</pingservices>
	<irisserver>
		<name>localdevelopment</name>
		<description>Development local server</description>
		<address>127.0.0.1</address>
		<loggingport>4560</loggingport>
		<rmiservice>//127.0.0.1/iris</rmiservice>
	</irisserver>
	<irisserver>
		<name>test_preas01</name>
		<description>Development local server</description>
		<address>preas01</address>
		<loggingport>4560</loggingport>
		<rmiservice>//preas01/iris</rmiservice>
	</irisserver>
	<irisserver>
		<name>prodserver_tdvas01</name>
		<description>Live server</description>
		<address>tdvas02</address>
		<loggingport>4560</loggingport>
		<rmiservice>//tdvas02/iris</rmiservice>
	</irisserver>
</irisclient>
